# sane defaults
set -g base-index 1
setw -g pane-base-index 1
set -g default-command zsh
setw -g mode-keys vi
unbind C-b                                                 # Unbind the default Ctrl-b prefix
set -g prefix `                                            # Set backtick as the prefix key
bind-key ` send-prefix                                     # Bind the backtick key to send the prefix command
bind '`' send-keys '`'
set -g status-style bg=default
set -g status-style fg=colour240                           # grey color for text
set -g status-position top
set-option -g history-limit 10000
set -g default-terminal "tmux-256color"                    # fix colors
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g extended-keys-format csi-u
set -g mouse on                                            # mouse support for pane resizing
set -g set-clipboard on                                    # copies to system clipboard
set -g status-justify left                                 # justify left

# rebinds
bind-key j select-pane -D
bind-key k select-pane -U
bind-key h select-pane -L
bind-key l select-pane -R
bind-key -n S-Left swap-window -t -1\; select-window -t -1
bind-key -n S-Right swap-window -t +1\; select-window -t +1
# Splits open in current directory
bind-key C-v split-window -h -c '#{pane_current_path}'
bind-key C-x split-window -v -c '#{pane_current_path}'
bind-key \\ select-window -l
bind-key + resize-pane -U 20
bind-key - resize-pane -D 20
bind-key > resize-pane -R 20
bind-key < resize-pane -L 20

# Automatically rename windows to show program name (or directory if shell)
set-window-option -g automatic-rename-format '#{?#{m/r:(fish|bash|zsh|sh)$,#{pane_current_command}},#{b:pane_current_path},#{pane_current_command}}'

# Vi mode key bindings for selection and copying
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi y send -X copy-selection
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"  # macOS example; replace with your clipboard tool
bind-key -Tcopy-mode-vi 'C-v' send -X begin-selection \; send -X rectangle-toggle

# Reload config with prefix + r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"
